outputdir/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Added_Date__c</fullName>
        <label>Added Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

force-app/main/default/classes/ProductTriggerHelper.cls
public class ProductTriggerHelper {
    public static void checkBeforeInsertUpdate(List<Product__c> productList){
        checkBefore(productList);
    }
    
    private static void checkBefore(List<Product__c> productList){
        List<Product__c> newProductList = productList;
        for(Product__c item : newProductList){
            if(item.Amount__c > 0){
                item.Available__c = true;
            }
            if(item.Amount__c == 0){
                item.Available__c = false;
            }
            if(item.Added_Date__c ==null){
                item.Added_Date__c = System.now();
            }
        }
    }
}