outputdir/objects/Product__c.object
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Added_Date__c</fullName>
        <label>Added Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Release_Date__c</fullName>
        <label>Release Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

force-app/main/default/classes/TestProductTrigger.cls
@isTest
public class TestProductTrigger {
static Product__c product = new Product__c();
    static List<Product__c> productList = new List<Product__c>();
    @isTest static void testFirst(){
        product.Name = 'Apple';
        product.Added_Date__c = System.now();
        product.Available__c = false;
        productList.add(product);
        insert productList;
        Product__c actualProduct = [SELECT Name,Price__c,Amount__c,Type__c,Added_Date__c,Release_Date__c,Available__c
                                           FROM Product__c WHERE Name = 'Apple'];
        
        
        System.assertEquals(String.valueOf(productList.get(0).Id), String.valueOf(actualProduct.Id));
    }
    @isTest static void testSecond(){
        
        productList.add(product);
        insert productList;
        
        productList.get(0).Name = 'NewName';
            
        Product__c actualProduct = [SELECT Name,Price__c,Amount__c,Type__c,Added_Date__c,Release_Date__c,Available__c
                                           FROM Product__c];
        
        actualProduct.Name = 'NewName';
        update actualProduct;
        System.assertEquals(productList.get(0).Name, actualProduct.Name);
    }
}